# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LCNavgation' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LCNavgation
pod 'Aspects', '~> 1.4.1'
pod 'RSSwizzle', '~> 0.1.0'

end
